# Generated by Django 5.2.14 on 2026-05-19 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Lucide icon name (e.g. Code, Database, Server)', max_length=50)),
                ('theme_color', models.CharField(help_text='CSS gradient or theme class', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('duration', models.CharField(help_text='Estimated time (e.g. 1-2 weeks)', max_length=50)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='roadmaps.career')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField(help_text='Link to the YouTube playlist or video')),
                ('resource_type', models.CharField(choices=[('youtube_playlist', 'YouTube Playlist'), ('youtube_video', 'YouTube Video'), ('article', 'Article/Documentation')], default='youtube_playlist', max_length=30)),
                ('duration', models.CharField(blank=True, help_text='e.g. 5 hours, 12 videos', max_length=50, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmaps.roadmapnode')),
            ],
        ),
    ]
